# Generated by Django 5.1.6 on 2025-03-13 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('can_create_event', 'Can create event'), ('can_edit_all_event', 'Can edit all events'), ('can_view_all_event', 'Can view all events'), ('can_delete_event', 'Can delete event')]},
        ),
        migrations.AlterField(
            model_name='event_registration',
            name='check_in_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.PositiveIntegerField()),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='eventservices.event')),
            ],
        ),
        migrations.AddField(
            model_name='event_registration',
            name='ticket_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventservices.tickettype'),
        ),
    ]
